### ISSUE TITLE
Site search error when selecting category from results Magento CE 1.8.1.0

### ISSUE THREAD

**Issue by ksaltik** [Smile-SA/smile-magento-elasticsearch#1]
Fatal error: Call to a member function getSearchQuery() on a non-object in C:\xampp\htdocs\oneyhosting.com\app\code\community\Smile\VirtualCategories\Model\Observer.php on line 57

**Comment by afoucret** [comment]
Looks like you don't enable the module into System > Catalog > Search or ES is not running.

Can you check ?

**Comment by afoucret** [comment]
Additional questions : 

* Did you proceed to a full reindex into Magento ?

* Did you install on a fresh Magento or in an existing project ? 

In the second case you should take a look your layouting since our module as strong rely on it's own layout files located into smile/elasticsearch.xml (to deals with Magento layer). The bug you describe make me think about an existing layout file in conflict with the one our module deliver.

**Comment by afoucret** [comment]
@ksaltik,

Any news about this issue ?

**Comment by afoucret** [comment]
Without response from you we can not go further on this.
So, I close the issue.
