### ISSUE TITLE
Can't Use Smile on AWS Elastic Search Service

### ISSUE THREAD

**Issue by deepusnath** [Smile-SA/smile-magento-elasticsearch#124]
Elastic Service of Amazon would always be the preferable option for someone who have their website on AWS.  As AWS Elastic Service doesn't allow to modify service configuration, plugins like "analysis-phonetic" and "analysis-icu" can't be installed there. This is a major limitation of smile-magento-elasticsearch that compel to go for alternate options. It will be better to have a workaround to make it available to existing Elastic Service of Amazon.

**Comment by romainruaud** [comment]
Hello @deepusnath .

Not being able to install plugins, and prevented to use some ES operations is in fact a limitation of AWS, not of smile-magento-elasticsearch.

AWS Elasticsearch is not a "real" Elasticsearch service since you are not able to customize it and cannot also run all standard ES operations : http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-es-operations.html

There is no support for the termvector operation which is used by ElasticSuite to detect spellchecked requests.

I close the issue since we consider us not responsible of a non standard ES implementation like is AWS one, and are not able to develop a workaround for it (required plugins are mandatory and the heart of this module, so does the termvector feature).

BR

**Comment by DevXeni** [comment]
I'm sorry, this is closed issue but I need to actualize this information.
This is info from AWS:
> 
/_termvectors (Index only)

I'm trying to install smile/elasticsuite on aws elasticsearch 5.5, after few minutes I've got "No alive nodes found in your cluster".

Plugins:
curl -XGET 'https://***us-east-1.es.amazonaws.com/_cat/plugins?pretty'
pfp9Rkr analysis-icu        5.5.2
pfp9Rkr analysis-kuromoji   5.5.2
pfp9Rkr analysis-phonetic   5.5.2
pfp9Rkr analysis-seunjeon   x.x.x.x
pfp9Rkr analysis-smartcn    5.5.2
pfp9Rkr analysis-stempel    5.5.2
pfp9Rkr analysis-ukrainian  5.5.2
pfp9Rkr discovery-ec2       5.5.2
pfp9Rkr elasticsearch-jetty 2.2.0
pfp9Rkr ingest-attachment   5.5.2
pfp9Rkr ingest-user-agent   5.5.2
pfp9Rkr mapper-attachments  5.5.2
pfp9Rkr mapper-murmur3      5.5.2
pfp9Rkr mapper-size         5.5.2
pfp9Rkr repository-s3       5.5.2
OwW3GjV analysis-icu        5.5.2
OwW3GjV analysis-kuromoji   5.5.2
OwW3GjV analysis-phonetic   5.5.2
OwW3GjV analysis-seunjeon   x.x.x.x
OwW3GjV analysis-smartcn    5.5.2
OwW3GjV analysis-stempel    5.5.2
OwW3GjV analysis-ukrainian  5.5.2
OwW3GjV discovery-ec2       5.5.2
OwW3GjV elasticsearch-jetty 2.2.0
OwW3GjV ingest-attachment   5.5.2
OwW3GjV ingest-user-agent   5.5.2
OwW3GjV mapper-attachments  5.5.2
OwW3GjV mapper-murmur3      5.5.2
OwW3GjV mapper-size         5.5.2
OwW3GjV repository-s3       5.5.2

I use endpoint from AWS ES: 

> smile/smile_elasticsuite_core_base_settings/servers  ***us-east-1.es.amazonaws.com

and 

> smile_elasticsuite_core_base_settings/es_client/enable_https_mode 1

because endpoind supports https.
Why I've got this message "No alive nodes found in your cluster"? 
But I can connect to endpoint as you can see above.
Please, maybe you can provide explanation?
Thank you for your excellent work :)

**Comment by blueflykeelo** [comment]
Were you able to figure this out? I have the exact same problem.

**Comment by DevXeni** [comment]
Hi!
Maybe here you can find an answer
https://github.com/Smile-SA/elasticsuite/issues/851 - (be carefull - magento2)

**Comment by blueflykeelo** [comment]
I am not using HTTPS, and I have port 80 in my URL. I will try to change it
to secure and set the port to 443

**Comment by DevXeni** [comment]
just write 80 instead 443 and http instead https

**Comment by blueflykeelo** [comment]
Yes, that is how I had it....still same error. I just tried with https and
443 and that doesnt work either.

**Comment by blueflykeelo** [comment]
curl works just fine for both

**Comment by blueflykeelo** [comment]
Is this how your config is set?

array (
  'servers' => 'https://MYAWSURL.es.amazonaws.com:443',
  'enable_https_mode' => '1',
  'enable_http_auth' => '0',
  'http_auth_user' => '',
  'http_auth_pwd' => '',
),
