### ISSUE TITLE
Enhancement: support for ES 2.x

### ISSUE THREAD

**Issue by simbus82** [Smile-SA/smile-magento-elasticsearch#53]
I see lot of new good commits. This extension is very useful!

Unfortunatly my provider give me a server with ES 2.x installed.

Can you help me to decide if i need to downgrade to a precise version of ES 1.x or if it is possible to let Smile-magento-elasticsearch work on ES 2.x?

Thanks a lot!

**Comment by afoucret** [comment]
Hi Simone,

As we explained in a previous issue, the support of ES 2.x is not our top priority at the moment.
Our focus is on the migration of the module for Magento 2.x instead.

The amount of works to get everything working with ES 2.x is quite important since we need to rewrite some parts of the faceting engine to use aggregations. 
Since it is not trivial at all, we decide to delay this work for a next release (maybe 1.5 or 1.6).

For now you should use the last stable release of the branch 1.7.x of ElasticSearch.

If your hosting provider can not provide an ES 1.x cluster, maybe would you be pleased to try the SaaS version of ES (the version 1.7.5 can still be chosen) : https://www.elastic.co/cloud

Note : If using the SaaS version of ES, don't forget to enable both  analysis-icu and analysis-phonetic plugins which are required by the module.

**Comment by simbus82** [comment]
You've answered perfectly my question.
I can ask without problem to my provider to install elastic search 1.7.x, as you said.
Thank you for the advice on elastic cloud, it can be very useful for some our projects!

Thanks a lot for your answer.

**Comment by romainruaud** [comment]
I close the issue since your question was answered.

Regards,
