### ISSUE TITLE
Error on catalogsearch result page if no VirtualRule is set

### ISSUE THREAD

**Issue by markus-g** [Smile-SA/smile-magento-elasticsearch#6]
If I enter a search query and press enter, I get this two error messages:

```
Fatal error: Call to a member function getSearchQuery() on a non-object in D:\xampp-5.5.19\htdocs\project_name\app\code\community\Smile\VirtualCategories\Model\Observer.php on line 57
```
```
Fatal error: Call to a member function getChildrenCategoryQueries() on a non-object in D:\xampp-5.5.19\htdocs\project_name\app\code\community\Smile\VirtualCategories\Model\Observer.php on line 85
```

is there something wrong with my configuration?

**Comment by afoucret** [comment]
One question, are you using flat catalog categories ?

**Comment by markus-g** [comment]
Yes, I do.

**Comment by afoucret** [comment]
The problem is related to the usage of the flat categories model.
I explain.

The virtual attribute has a backend model which is mostly in charge of the rule unserialization. Because of inconsistencies in Magento code, backend model are not executed in front when using flat categories. The patch you submitted yesterday will not do the job and at least virtual categories will not work with it (always in the context of the flat catalog).

We should be able to use an observer to to the job of forcing the execution of the afterLoad function of backend model of the attribute. It is crappy but we do not have the choice giving the Magento code is not consistent. I don't like this option because it would require us to check all our features works well with flat catalog (product, categories or mixed). It is kind of a race to append more and more observers that will made the code more complex.

Flat categories is something we usually don't enable on our website because of the difference of behaviour that can be introduced by it's usage as explained above. It is the same for flat products. My personal advice on this is to keep these feature disabled to avoid such a bug that is very hard to debug.

I think it would be better to update the documentation to make flat catalog an officially unsupported feature. What do you think of this ?

Bonus: our internat benchmarks have shown that using flat catalog does not provides significant performance improvement when using it with a search engine (SolR or ElasticSearch). The EAV heavy usage of join clauses usually killing performance is counterbalanced by the fact you have a very precise where clause limiting the number of products to get loaded.

**Comment by markus-g** [comment]
Thank you for your explanation.
If I deactivate flat catalog categories, it is working much better and I get filters too.

>
I think it would be better to update the documentation to make flat catalog an officially unsupported feature. What do you think of this ?
>
I think it is essential to put this information into the documentation, because without, the extension at the moment simply doesn't work.

**Comment by afoucret** [comment]
I change my mind since I have a lot of questions about this.

The module should be compatible with flat categories since commit fbf909ee3187c0c3ca485f967a4ae386cf6a2e6c
