### ISSUE TITLE
QUESTION: Is it possible with the ElasticSearch module to do partial reindexing ?

### ISSUE THREAD

**Issue by diglin** [Smile-SA/smile-magento-elasticsearch#65]
Hi,

 We have Magento 1.14 EE and it looks like that each time it needs a full reindex of the Elastic Search index. Is there any way to do a partial reindexing ?

**Comment by romainruaud** [comment]
Hello,

could you please develop what is exactly happening ? The module supports partial reindexing (Mview or not).

Best regards,

**Comment by diglin** [comment]
Hi,

Thank you for your feedback.

Magento EE does a reindexing via cron job and update product price, category and so on ONLY for updated data or entities. Not for the full catalog. That's the purpose of a partial reindexing. Preventing to reindex all as it's time consuming. 

The ElasticSearch Module use the catalogsearch mview metadata to reindex. The reindexing works as the following:
- As soon as a cron job is started, the reindexing of the catalogsearch is started (I'm not sure in this case if it is only when product data has changed or in any cases).
- When it's running, the status of the view_name 'catalogsearch_fulltext_cl' of the DB table 'enterprise_mview_metadata' has a value of 3 which means that the reindex is running.
- On Elastic Search side, the current index doesn't change and is still used by the Search engine which is ok (although I had an other issue but it should be part of a separated issue in github - it happened sometimes that the current index is deleted before the new index is done and then no more product was found via the search).
- An other index in ES is created and the whole catalog is again indexed. It doesn't do a copy and then apply only changes, it creates a new fresh index. Which takes around 15 until 20 minutes in my case with a catalog of around 5000 Products (enabled and in stock).

From my point of view, it doesn't respect the philosophy of partial reindexing to reindex only what is needed to be reindexed in the purpose to save time. It reindex all

Best regards
Sylvain

**Comment by romainruaud** [comment]
Hello Sylvain and thank you for this detailed explanation of the issue.

I will take a look at it, try to reproduce this behavior and then provide a fix. If this behavior is confirmed, you are right, this should not process this way and rebuild index for the whole catalog, but only reindex products that are in the changelog queue.

Regards,

**Comment by romainruaud** [comment]
Hello Sylvain,

unfortunately, I am not able to reproduce your issue, neither on this master branch, nor on our internal 1.4 (next release) branch.

This basic test case is ok : 

- Set catalogsearch fulltext indexer to "Update when scheduled" on the Index Management tab of the Configuration.
- Save a random bunch of products.
- Product Ids are showing up in the "catalogsearch_fulltext_cl" table.
- Launch the cron
- The cron rebuilds index for previously changed products. No new ES index is created.

In which cases could Magento process a full reindex by the cron ? If you look on `Enterprise_Index_Model_Observer::refreshIndex()` you will see that this cron process a full reindex for thoses considered as "inactive" : they are wrongly called "inactive" because in fact they are indexers that have an "INVALID" status (you can look at `Enterprise_Index_Model_Observer::_getInactiveIndexersByPriority()` ).

=> If something has invalidated the catalogsearch_fulltext index, Magento will process a full reindex on the next cronjob.

This may be what is happening to you. Could you check if something is invalidating your index ? 

Regards,

**Comment by diglin** [comment]
Hi

Do not close this issue and let me some time to give you more details

Thanks

**Comment by romainruaud** [comment]
Sorry but I close this one due to being inactive for too long.

Feel free to reopen if you have any additional comments.
