### ISSUE TITLE
create condition programmatically

### ISSUE THREAD

**Issue by JeromeSiau** [Smile-SA/smile-magento-elasticsearch#83]
Hi,

I'm trying to create brand page programmatically but i don't find how to do.

Do you have any example of create a category with virtual_categories on a simple condition (like manufacturer = 1) in a script ?

Thx

**Comment by romainruaud** [comment]
Hello @Jerome38 .

We experienced a such thing. But finally we conclude that it's NOT a good idea to create a whole bunch of virtual categories programmatically. Especially to manage brands/manufacturer which was exactly the case we did test.

In our opinion, you'd better go using a custom controller/router to build a nice Url for your brand pages, then using the same layout as a category and just use a fulltext product collection with the proper filter on the brand applied.

If you persist on creating categories, you will also obtain a doublon : there will be a "manufacturer" filter which has no sense since you can also browse by categories.

Regards,

**Comment by romainruaud** [comment]
I close this one since I have nothing more to add to previous answer.

Please free to open other issues if needed @Jerome38
