### ISSUE TITLE
Debian + Magento 1.9.2.4 + Apache + ElasticSearch 2.4

### ISSUE THREAD

**Issue by danielr1979** [Smile-SA/smile-magento-elasticsearch#85]
I install smile's elasticSearch extention to Magento 1.9 but does not show detail for your configuration and does not show the option to search engine. No exception or error is generated. What I can do?

**Comment by romainruaud** [comment]
Hello @danielr1979 and thank you for trying our module.

How did you install it ? With modman ? Please give us more details.

Best regards,

**Comment by danielr1979** [comment]
Hello

I copy all file in Smile's src folder into Magento's main folder, but it
doesn't show anything in admin panel.

Can you help me please?

**Comment by danielr1979** [comment]
Hi, i did it!

The problems was folder`s permisology. But now, when i try to index catalog
search index, generate the following error:
{"error":{"root_cause":[{"type":"index_creation_exception","reason":"failed
to create index"}],"type":"illegal_argument_exception","reason":"Unknown
TokenFilter type [phonetic] for [beidermorse_en]"},"status":400}

I have installed analysis-phonetic plugin..

What i can do?

sorry about my bad english

**Comment by romainruaud** [comment]
Glad to here that you managed to install the module :)

Now it seems your are missing the required modules for ElasticSearch.

They are : 
- analysis-phonetic
- analysis-icu

Did you launch the "install-es.sh" script ? It should install these modules. Please refer to the documentation about it : https://github.com/Smile-SA/smile-magento-elasticsearch/blob/master/doc/install.md

The script is made for Debian so it should do the trick for you.

If it does not work (since it has been written for an old version of Debian), you just need to reproduce what is done in the script.

If you need help, tell me, I'll write a quick guide about installing it manually.

Regards

**Comment by danielr1979** [comment]
Hi,

Yes, I did. I launch the "install-es.sh" script and I have both plugin
installed..
The ES service run perfect but the error persist when i try to launch the
Magento's reindex. What can i do?

**Comment by romainruaud** [comment]
Did you restart ES after installing the plugin ?

**Comment by romainruaud** [comment]
@danielr1979 any update about this one ?

**Comment by romainruaud** [comment]
I close this one due to inactivity.

@danielr1979 feel free to reopen it if you need more help.

Best regards,
