### ISSUE TITLE
Elasticsearch index changes during mass import causes empty pages.

### ISSUE THREAD

**Issue by jvdoaerobertics** [Smile-SA/smile-magento-elasticsearch#86]
Hi,

I'm importing products in my magento store using the danslo ApiImport module.
(https://github.com/danslo/ApiImport). It seems when I run the importer (and the products are being changed) that the products are being removed from the elastic index. Of course I can run a reindex in the end. But the problem is that in the time between the import and the full reindex no single product is displayed on the website.

What would be the best way to solve this problem? 

Thanks in advance!

**Comment by romainruaud** [comment]
Hello,

I'm afraid that we do not support third party modules integration with our own.

Your module is probably doing something wrong during import.

At our side, when you are processing a full reindex, we are still querying the "old" one since the new index is ready, to ensure there is no service interruption.

Maybe your import module is deleting products during import phase, which could cause them to disappear from ES index.

I close the issue since it is not related to our module.

Regards,
